name: CD
on:
  workflow_call:

jobs:
  Build_and_Publish_a_Docker_image:
    environment: Production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master
      - uses: actions/setup-node@v3
        with:
          node-version: "19"
      - name: Get current package version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Install doctl
        uses: digitalocean/action-doctl@v2.3.0
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Authenticate to DigitalOcean
        run: doctl registry login --expiry-seconds 600
      - name: Build and push image
        run: |-
          npm run build-do
          npm run push-do
      - name: DigitalOcean App Platform deployment
        uses: digitalocean/app_action@v1.1.4
        with:
          app_name: trellzo-web
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          images: '[
            {
            "name": "trellzo-web",
            "image":{
            "registry_type": "DOCR",
            "repository": "trellzo-web",
            "tag": "${{ steps.package-version.outputs.current-version }}"
            }
            }
            ]'
