name: CI/CD
on:
  push:
    branches: [main]

jobs:
  CI:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    uses: ./.github/workflows/ci.yml
    secrets: inherit
  CD:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    needs: CI
    uses: ./.github/workflows/cd.yml
    secrets: inherit
